---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-vlan-100
spec:
  nodeSelector: {}
  desiredState:
    interfaces:
      # VLAN interface on physical NIC
      - name: vlan-100
        type: vlan
        state: absent
        vlan:
          base-iface: enp1s0
          id: 100
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 10.2.100.101
              prefix-length: 24
      - name: vrf-100
        type: vrf
        state: absent
        vrf:
          # Attach the VLAN interface to this VRF
          port:
            - vlan-100
          # Must be < 1000 on OpenShift
          route-table-id: 100
