---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-t1ns1-ubipod
  namespace: t1ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ubipod
  template:
    metadata:
      labels:
        app: app-ubipod
        # Attach a cudn to this deployment's pod:
      annotations:
        k8s.v1.cni.cncf.io/networks: cudn-ipam-on-vlan100
    spec:
      containers:
        - name: container-ubipod
          image: registry.access.redhat.com/ubi9/ubi
          command: ["sleep", "infinity"]
